bot: {admin_passphrase: 'bm9wYXNkd29yZGZvcm9sZG1lbg==

    ', answer-forbidden: false, answer-unknown: false, approved_chat: -1001050462991,
  autohandbrake: false, connection_problems: false, download-file-path: 'https://api.telegram.org/file/bot{key}/{file_id}',
  field_ids: 'kc4KJpqv

    ', field_passphrase: 'RnJpZGF5TmlnaHQ=

    ', get-file-path: 'https://api.telegram.org/bot{key}/getFile?file_id={file_id}',
  group_chat_name: "\u0422\u0435\u0441\u0442", kc_ids: 'kA==

    ', kc_passphrase: 'Z29nb2dzZ28=

    ', log_activity: true, obfuscation_id: 'kc4KJpqv

    ', paused: false, send-document-path: 'https://api.telegram.org/bot{key}/sendDocument',
  send-message-path: 'https://api.telegram.org/bot{key}/sendMessage', send_task_to_private: true,
  tag_field: true, token: !!python/unicode '580878914:AAE0O28NU1M4Nese6CcUGvanOPA8YGzpx_Q',
  updates-path: 'https://api.telegram.org/bot{key}/getUpdates?offset={offset}', users-path: 'https://api.telegram.org/bot{key}/getChat?chat_id={user_id}'}
